name: local_codeformer_x2
runtime:
  device: cpu
  resume: false
  seed: 1234
paths:
  input_root: C:/Users/kumi/Desktop/SR_HR_IMG/LR
  output_root: ./data/outputs/local_codeformer_x2
source:
  type: ImageFolderSourceReader
  recursive: true
  exts: [jpg, jpeg, png, webp]
tasks:
  - name: teacher_face_codeformer
    enabled: true
    type: TeacherSRGenerator
    runner:
      type: CodeFormerRunner
    model:
      name: CodeFormer_x2
      weights: ./weights/CodeFormer_x2.pth
      repo_root: ./third_party/CodeFormer
      facelib_root: ./third_party/facexlib
      basicsr_root: ./third_party/BasicSR
      download_url: https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth
      scale: 2
      fidelity_weight: 0.7
      face_upsample: true
      background_upsampler: null
      half: false
    output:
      folder_name: CodeFormer_x2
      target_type: pseudo_gt
