name: plant_mixed_hat_x2
runtime:
  device: cpu
  resume: true
  seed: 1234
paths:
  input_root: D:/SR数据集/网络数据集收集归类/绿植/style_diverse_mixed_sources_1200plus
  output_root: ./data/outputs/plant_mixed_teacher_x2
source:
  type: ImageFolderSourceReader
  recursive: true
  exts: [jpg, jpeg, png, webp]
tasks:
  - name: teacher_sr_hat
    enabled: true
    type: TeacherSRGenerator
    runner:
      type: HATAdapter
    model:
      name: HAT_SRx2
      weights: ./weights/HAT_SRx2.pth
      download_url: https://huggingface.co/jaideepsingh/upscale_models/resolve/main/HAT/HAT_SRx2.pth?download=true
      repo_root: ./third_party/HAT
      basicsr_root: ./third_party/BasicSR
      scale: 2
      tile: 256
      tile_pad: 16
      half: false
      patch_size: 1
      img_size: 64
      window_size: 16
      img_range: 1.0
      depths: [6, 6, 6, 6, 6, 6]
      embed_dim: 180
      num_heads: [6, 6, 6, 6, 6, 6]
      compress_ratio: 3
      squeeze_factor: 30
      conv_scale: 0.01
      overlap_ratio: 0.5
      mlp_ratio: 2.0
      upsampler: pixelshuffle
      resi_connection: 1conv
    output:
      folder_name: HAT_SRx2
      target_type: pseudo_gt
