name: scut_face_gfpgan_x2
runtime:
  device: cpu
  resume: false
  seed: 1234
paths:
  input_root: D:/SR数据集/网络数据集收集归类/人脸/academic_SCUT_FBP5500_Asian_modern_100
  output_root: ./data/outputs/scut_face_gfpgan_x2
source:
  type: ImageFolderSourceReader
  recursive: true
  exts: [jpg, jpeg, png, webp]
tasks:
  - name: teacher_face_gfpgan
    enabled: true
    type: TeacherSRGenerator
    runner:
      type: GFPGANRunner
    model:
      name: GFPGAN_x2
      weights: ./weights/GFPGAN_x2.pth
      repo_root: ./third_party/GFPGAN
      facelib_root: ./third_party/facexlib
      basicsr_root: ./third_party/BasicSR
      download_url: https://github.com/TencentARC/GFPGAN/releases/download/v1.3.4/GFPGANv1.4.pth
      scale: 2
      arch: clean
      channel_multiplier: 2
      has_aligned: false
      only_center_face: false
      paste_back: true
      weight: 0.5
      bg_upsampler: null
      half: false
    output:
      folder_name: GFPGAN_x2
      target_type: pseudo_gt
